### PR TITLE
Add python 3.9 to matrix test

### PR DESCRIPTION
**Pull request by inverse**
## Proposed change

Python 3.9 got released recently - lets see how well it performs under tests

See: https://docs.python.org/3.9/whatsnew/3.9.html

## How to test the change

N//A

## Checklist

-   [x] Tests have been added to verify that the new code works (if possible)
-   [ ] Documentation has been updated to reflect changes

### CODE REVIEW

**Comment by valayDave** [comment]
Seems like it works for 3.9. Tests have Passed. Should we need to add anything to the docs ?

**Comment by inverse** [comment]
So you mean adding an entry here: https://github.com/valayDave/tell-me-your-secrets/blob/master/setup.py#L53

or something else?

**Comment by valayDave** [comment]
Yes. I think just that should be fine.

**Comment by inverse** [comment]
Updated

**Review by valayDave — APPROVED** [review]

**Pull request merged**
