### PR TITLE
Poetry + Python 3.10 + Drop 3.6

### PR DESCRIPTION
**Pull request by inverse**
## Proposed change

- Migrate to poetry
- Add support for Python 3.10
- Drop Python 3.6 as it's EOL

## How to test the change

Should just work as before just using poetry to manage dependencies.

```
poetry install
poetry shell
python tell_me_your_secrets/__main__.py 
```

## Checklist

-   [ ] Tests have been added to verify that the new code works (if possible)
-   [x] Documentation has been updated to reflect changes
-   [x] Changelog has been updated to reflect changes

### CODE REVIEW

**Comment by valayDave** [comment]
Out of curiosity, why are we stopping 3.6 support? I understand that it has reached EOL but I don't think our code has breaking changes that wouldn't work for 3.6. Additionally even though it is EOL there are considerable [amounts of downloads](https://discuss.python.org/t/python-download-stats-for-march-2022/14908) for 3.6 which makes me question if we should remove it just yet. What do you think ?

**Comment by inverse** [comment]
You are correct - there is nothing breaking about these changes however it encourages people to use end of life software which could lead to security issues.

Poetry provides a way to lock dependencies between multiple python versions so that dependencies are consistent. Check the lock file.

Trying to adapt it to be able to resolve the dependencies for Python 3.6 but it's taking a long time :/

**Comment by valayDave** [comment]
If it is taking too long then it's totally fine if we don't include it :). PR looks good to me

**Comment by inverse** [comment]
I know sometimes there are some performance issues with Poetry with these sorts of wide version SAT solving. 

e.g. https://github.com/python-poetry/poetry/issues/2094

**Review by valayDave — APPROVED** [review]

**Pull request merged**
